"""
``gpt-simple init`` subcommand.

Generates a commented YAML config template.
"""

from __future__ import annotations

import argparse
import logging
import sys

logger = logging.getLogger("gpt_simple")

# ---- presets (model-only overrides) ----------------------------------------

_PRESETS: dict[str, dict] = {
    "small": {
        "description": "~125M parameters",
        "model": {"n_embd": 768, "n_layer": 12, "n_head": 12, "n_positions": 2048},
    },
    "medium": {
        "description": "~350M parameters",
        "model": {"n_embd": 1024, "n_layer": 24, "n_head": 16, "n_positions": 2048},
    },
    "large": {
        "description": "~1.3B parameters",
        "model": {"n_embd": 2048, "n_layer": 24, "n_head": 32, "n_positions": 2048},
    },
}


def _template(preset_name: str | None = None) -> str:
    """Return the commented YAML template string."""
    if preset_name and preset_name in _PRESETS:
        p = _PRESETS[preset_name]
        m = p["model"]
        model_block = f"""\
model:
  # Preset: {preset_name} ({p['description']})
  n_embd: {m['n_embd']}
  n_layer: {m['n_layer']}
  n_head: {m['n_head']}
  n_positions: {m['n_positions']}
  dropout: 0.0
  # n_kv_head: null         # null = MHA; < n_head = GQA; 1 = MQA
  use_bias: false           # global default for all linear biases
  # qkv_bias: null          # override Q/K/V bias (Qwen2: true)
  # attn_out_bias: null     # override attention output-projection bias
  # mlp_bias: null          # override MLP bias
  activation: swish         # swish | gelu | relu
  mlp_type: gated           # gated (SwiGLU/GeGLU) | mlp (vanilla, e.g. GPT-2)
  # intermediate_size: null # explicit FFN width; null = derived from n_embd
  norm: rmsnorm             # rmsnorm | layernorm
  norm_eps: 1.0e-5
  tie_word_embeddings: true # false = separate LM head (e.g. real Llama)
  rope_base: 10000.0
  attention_mode: causal    # causal | sdpa_mask | flex"""
    else:
        model_block = """\
model:
  # vocab_size is inferred from the tokenizer and padded to 128
  n_embd: 768
  n_layer: 12
  n_head: 12
  n_positions: 2048
  dropout: 0.0
  # n_kv_head: null         # null = MHA; < n_head = GQA; 1 = MQA
  use_bias: false           # global default for all linear biases
  # qkv_bias: null          # override Q/K/V bias (Qwen2: true)
  # attn_out_bias: null     # override attention output-projection bias
  # mlp_bias: null          # override MLP bias
  activation: swish         # swish | gelu | relu
  mlp_type: gated           # gated (SwiGLU/GeGLU) | mlp (vanilla, e.g. GPT-2)
  # intermediate_size: null # explicit FFN width; null = derived from n_embd
  norm: rmsnorm             # rmsnorm | layernorm
  norm_eps: 1.0e-5
  tie_word_embeddings: true # false = separate LM head (e.g. real Llama)
  rope_base: 10000.0
  attention_mode: causal    # causal | sdpa_mask | flex"""

    return f"""\
# GPT-Simple configuration
# Generated by: gpt-simple init
# Docs: https://github.com/<your-org>/gpt-simple
#
# Quick start
#   1. Edit data.path / data.tokenizer below.
#   2. Run:    gpt-simple train --config this_file.yaml
#   3. Stop:   gpt-simple stop  --output_dir ./outputs
#   4. Resume: re-run step (2) — `training.resume: auto` picks up
#              the latest checkpoint automatically.
#
# For SLURM / Kubernetes / loop-based orchestration patterns see
# examples/orchestrators/ in the repo.

# ── Model architecture ──────────────────────────────────────────
{model_block}

# ── Data pipeline ───────────────────────────────────────────────
data:
  path: ./data/tokenized    # root directory with .bin/.idx shards
  tokenizer: gpt2           # HuggingFace name or local path
  format: pretokenized      # pretokenized | jsonl
  max_length: 2048
  packing: true
  num_workers: 4
  # curriculum:              # omit for uniform sampling
  #   - duration_tokens: 5_000_000_000
  #     mix: {{web: 0.6, code: 0.2, math: 0.1, wiki: 0.05, qa: 0.05}}
  #   - duration_tokens: 5_000_000_000
  #     mix: {{web: 0.3, code: 0.3, math: 0.2, wiki: 0.1, qa: 0.1}}

# ── Optimizer & LR schedule ─────────────────────────────────────
optimizer:
  learning_rate: 3.0e-4
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  eps: 1.0e-8
  max_grad_norm: 1.0
  warmup_steps: 100
  # decay_steps: null       # null → max_steps - warmup_steps
  min_lr_ratio: 0.1

# ── Training run ────────────────────────────────────────────────
training:
  per_device_batch_size: 4
  gradient_accumulation_steps: 4
  max_steps: 1000
  gradient_checkpointing: true
  compile: true
  seed: 42
  logging_steps: 10
  eval_steps: 500
  save_steps: 1000
  # max_eval_batches: null
  output_dir: ./outputs
  resume: auto              # auto (default) | scratch | <checkpoint path>
                            # - auto: pick the latest checkpoint, else start fresh
                            # - scratch: refuse to clobber existing checkpoints
                            #   (use `gpt-simple train --force` to wipe + start)
  keep_last_k: 3            # rolling buffer of recent checkpoints (null = keep all)
  # keep_milestone_every: null   # extra: keep one ckpt every N steps (e.g. 10_000)
  # Wall-clock budget — the trainer saves a graceful checkpoint and exits 0
  # `walltime_reserve_seconds` before the deadline.  Resolution order:
  #   1. `max_runtime_seconds` (this field, if set)
  #   2. $SLURM_JOB_END_TIME   (auto on SLURM clusters)
  #   3. $GPT_SIMPLE_MAX_RUNTIME (generic / Kubernetes / Docker)
  # max_runtime_seconds: null
  walltime_reserve_seconds: 300
  # mixed_precision: null    # auto (bf16 on Ampere+; fp16 on V100/T4; no on CPU)
  #                          # set explicitly: "bf16" | "fp16" | "no"
  # wandb_project: null
  # wandb_run_name: null
"""


class InitCommand:
    @staticmethod
    def register(subparsers: argparse._SubParsersAction) -> None:
        p = subparsers.add_parser(
            "init",
            help="Generate a config template",
            description="Write a commented YAML config to stdout or a file.",
        )
        p.add_argument(
            "--output", "-o", type=str, default=None,
            help="Write config to this file instead of stdout",
        )
        p.add_argument(
            "--preset", type=str, default=None,
            choices=list(_PRESETS.keys()),
            help="Use a preset model size (small/medium/large)",
        )
        p.set_defaults(func=InitCommand.run)

    @staticmethod
    def run(args: argparse.Namespace) -> None:
        text = _template(preset_name=args.preset)

        if args.output:
            from pathlib import Path
            Path(args.output).write_text(text, encoding="utf-8")
            logger.info(f"Config written to {args.output}")
        else:
            sys.stdout.write(text)
